import { GoogleGenAI, Type } from "@google/genai";
import { AgentType, AgentResponse } from '../types';

// Ensure process.env is handled safely for build environments, but strictly use the variable as requested.
const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

// Schema definition for the structured output
// Cast to any to avoid strict Schema type validation errors during build
const responseSchema: any = {
  type: Type.OBJECT,
  properties: {
    agentType: {
      type: Type.STRING,
      enum: [AgentType.RME, AgentType.ADMIN, AgentType.CLINICAL, AgentType.EDUCATION],
      description: "The specific sub-agent selected to handle the request."
    },
    reasoning: {
      type: Type.STRING,
      description: "Analisis Koordinator: Identifikasi tujuan dan justifikasi pemilihan agen."
    },
    content: {
      type: Type.STRING,
      description: "The textual response generated by the selected sub-agent (Tindakan Sub-Agen)."
    },
    structuredDataContext: {
      type: Type.STRING,
      description: "A valid JSON string containing specific data (e.g., agingSchedule, extractedFields, riskAssessment, keyPoints) tailored to the agent type."
    }
  },
  required: ["agentType", "reasoning", "content"]
};

const SYSTEM_INSTRUCTION = `
[ROLE PROFILE]
Anda adalah Koordinator Sistem Agen AI untuk Rumah Sakit (MediCore). Tugas Anda adalah menganalisis permintaan pengguna, menentukan tujuan fungsionalnya, dan merutekannya dengan spesifik dan akurat ke sub-agen yang bertanggung jawab.

[ARAHAN KEPATUHAN & DATA]
1. Standar Data: Wajib memproses data klinis menggunakan format standar kesehatan (DICOM, FHIR, HL7v2).
2. Keamanan: Pertahankan prinsip Kerahasiaan, Integritas, dan Ketersediaan (CIA).
3. Oversight Klinis: Output AI adalah alat bantu, keputusan akhir ada pada profesional medis.

[FUNGSI SUB-AGEN]

1. RME (Rekam Medis Elektronik / EMR):
   - Tugas: Mengelola data pasien, coding ICD-10, kepatuhan Permenkes No 24 Tahun 2022.
   - Output Data (JSON): 'extractedFields' (patientName, diagnosis, icdCode, plan).

2. ADMIN (Accounting & Administrative / AIS):
   - Tugas: Manajemen finansial, klaim BPJS, Piutang (Aging Schedule 30-150 hari).
   - Output Data (JSON): 'agingSchedule' (array of {period, amount, riskLevel}).

3. CLINICAL (Clinical Decision Support):
   - Tugas: Analisis citra medis (Vision), diagnosis banding, peringatan nilai kritis.
   - Output Data (JSON): 'riskAssessment' (array of {metric, value, status}).

4. EDUCATION (Patient Education):
   - Tugas: Edukasi pasien, penyederhanaan jargon medis, informed consent.
   - Output Data (JSON): 'keyPoints' (array of {topic, explanation, icon}).

[STRUKTUR OUTPUT PERMINTAAN]
Berikan respons dalam format JSON yang valid sesuai schema.
- Field 'reasoning': Isi dengan [Analisis Koordinator] dan [Perutean & Justifikasi].
- Field 'content': Isi dengan [Tindakan Sub-Agen] dalam bahasa yang sesuai (Formal/Klinis/Edukatif).
- Field 'structuredDataContext': Isi dengan JSON String data visualisasi yang relevan.
`;

export const processHospitalRequest = async (prompt: string, imageBase64?: string): Promise<AgentResponse> => {
  if (!apiKey) {
    return {
      agentType: AgentType.COORDINATOR,
      reasoning: "API Key missing. Simulating response.",
      content: "Please configure your Google Gemini API Key to enable the AI agents.",
      timestamp: new Date().toISOString()
    };
  }

  try {
    const parts: any[] = [];
    
    // Add image if present
    if (imageBase64) {
      parts.push({
        inlineData: {
          mimeType: "image/jpeg", // Assuming JPEG for simplicity, or detect from base64 header
          data: imageBase64
        }
      });
    }

    // Add text prompt
    parts.push({ text: prompt });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: { parts: parts },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        temperature: 0.4, 
      }
    });

    let jsonText = response.text || "";
    // Sanitize markdown if present
    jsonText = jsonText.replace(/^```json\s*/, "").replace(/\s*```$/, "");
    
    if (!jsonText) throw new Error("Empty response from AI");

    const parsed = JSON.parse(jsonText);
    
    let structuredData = null;
    try {
        if(parsed.structuredDataContext) {
            structuredData = JSON.parse(parsed.structuredDataContext);
        }
    } catch (e) {
        console.warn("Failed to parse structured data context", e);
    }

    return {
      agentType: parsed.agentType as AgentType,
      reasoning: parsed.reasoning,
      content: parsed.content,
      structuredData: structuredData,
      timestamp: new Date().toISOString()
    };

  } catch (error) {
    console.error("AI Service Error:", error);
    return {
      agentType: AgentType.COORDINATOR,
      reasoning: "System Error encountered during processing.",
      content: "Maaf, terjadi kesalahan sistem saat memproses permintaan Anda. Silakan coba lagi.",
      timestamp: new Date().toISOString()
    };
  }
};